name: Build TDLib

on:
  push:
    branches:
      - main

jobs:
  build-jvm-macos-arm64:
    runs-on: macos-15
    steps:
      - name: Setup dependencies
        run: brew install gperf cmake openssl coreutils openjdk

      - name: Clone TDLib
        run: git clone https://github.com/tdlib/td.git

      - name: Build TDLib
        run: |
          cd td
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DJAVA_HOME=/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home/ -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl/ -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td -DTD_ENABLE_JNI=ON -DTD_JSON_JAVA=ON ..
          cmake --build . --target install
          cd ../example/java
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DJAVA_HOME=/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home/ -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DTd_DIR:PATH=$(greadlink -e ../td/lib/cmake/Td) -DTD_ENABLE_JNI=ON -DTD_JSON_JAVA=ON ..
          cmake --build . --target install
